### ISSUE TITLE
是否可以添加支持oh-my-zsh

### ISSUE THREAD

**Issue by Ericliu68** [linrongbin16/lin.vim#10]
简单查看linvim不知道怎么去改，添加oh-my-zsh支持

**Comment by linrongbin16** [comment]
最早我自己是直接集成了oh-my-zsh，但是在使用过程中，有几次更新oh-my-zsh之后terminal卡死，所以去掉了oh-my-zsh。暂时应该也不会加进去。

安装完lin.vim之后，会自动生成 `~/.linvimrc` 文件，并在`~/.zshrc`中`source ~/.linvimrc`。
如果想加入oh-my-zsh，你可以先把`.linvimrc` 中的`PROMPT` 和 `CLICOLOR` 两个选项删除。
然后正常安装 oh-my-zsh 就行了，别忘了最后在 `~/.zshrc` 中加入 `source ~/.linvimrc`。
