### ISSUE TITLE
E484: 无法打开文件 /Users/xiaowangzi/.vim/vim-plug.vim

### ISSUE THREAD

**Issue by WDayu** [linrongbin16/lin.vim#11]
你好，谢谢你的分享，我在安装时遇到了以下的问题，我不知道该怎么解决，希望你能够为我解答一下。第一次提issues，不知道需要展示一些什么信息，以下是你可能需要的信息：
<img width="598" alt="截屏2021-11-12 下午6 37 46" src="https://user-images.githubusercontent.com/43671213/141453609-83e18f36-085d-4602-ae0a-6b93baf676f4.png">

<img width="571" alt="截屏2021-11-12 下午6 33 32" src="https://user-images.githubusercontent.com/43671213/141453118-df38eeab-15c2-4f0d-a78e-7685b14f9615.png">

**Comment by linrongbin16** [comment]
能提供安装过程的整个console的log么？

**Comment by Frandy** [comment]
在install.sh里面， cp vim-plug.vim挪到vim -c "PlugInstall" -c "qall"前面.应该能解决这个问题
ln -s ~/.vim/lin.vim ~/.vimrc
vim -c "PlugInstall" -c "qall"

"install user custom
cp ~/.vim/template/vim-plug-template.vim ~/.vim/vim-plug.vim

**Comment by linrongbin16** [comment]
的确，已经改了
