### ISSUE TITLE
clangd is not found

### ISSUE THREAD

**Issue by Frandy** [linrongbin16/lin.vim#13]
When try it on fedora35 workstation, got error for clangd not found, and failed to auto format when save file.
Found it need install clang-extra-tools. 
建议在install/fedora.sh里面添加安装语句.

**Comment by linrongbin16** [comment]
`sudo dnf install -y clang-extra-tools` 这个可以么？

**Comment by Frandy** [comment]
嗯, 可以

**Comment by linrongbin16** [comment]
ok已经改了
