### ISSUE TITLE
nerdtree自动关闭和自动退出focus

### ISSUE THREAD

**Issue by Frandy** [linrongbin16/lin.vim#14]
Hi， 

nerdtree的设置可以改善一下？
1. 只剩一个NERDTree Tab时自动退出
2. 打开一个文件，显示NERDTree之后，focus要回到文件

user_setting里有一些设置，不过没有达到上面的效果，参照NERDTree github上的指示，可以使用下面两个设置
" Close the tab if NERDTree is the only window remaining in it.
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
" Start NERDTree. If a file is specified, move the cursor to its window.
autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif

不过也不确定跟已经有的设置是否有冲突，放在后面是达到预期效果了.

Best wishes,

**Comment by linrongbin16** [comment]
nerdtree的配置可以你直接在user-settings.vim文件里nerdtree那个部分修改，覆盖默认配置就行。

user-settings.vim本来就是方便用户自定义的。

**Comment by Frandy** [comment]
嗯，好的.
