### ISSUE TITLE
安装过程中遇到这样的错误，请大佬指点

### ISSUE THREAD

**Issue by fgqile** [linrongbin16/lin.vim#16]
![image](https://user-images.githubusercontent.com/64899378/158744874-a32d029d-3615-4e71-b4e4-7d58ae2de422.png)

**Comment by tan-wei** [comment]
So what is your Python3 version? Python 3.6+ is required.

**Comment by linrongbin16** [comment]
@tan-wei  is correct, please try to use latest ubuntu and python3
