### ISSUE TITLE
[Question] Can we install only for vim or neovim?

### ISSUE THREAD

**Issue by tan-wei** [linrongbin16/lin.vim#17]
Thanks for this distribution.

For me, I want to use Neovim with my own configuration. And use `lin.vim` in Vim. I want to know whether the installation support one of Neovim and Vim, instead both of them.

**Comment by tan-wei** [comment]
Seems not supported now. But I can manually remove the symlink `vim.init` in the directory to satisfy my requirement.

**Comment by linrongbin16** [comment]
Yeah, not support now. bash environemnt management is not an easy thing

**Comment by tan-wei** [comment]
Got it. But I think my requirement is not that common, it is not needed for most people.
