### ISSUE TITLE
能否支持一下centos

### ISSUE THREAD

**Issue by Leo225** [linrongbin16/lin.vim#2]
这个vim我在macos已经使用，感觉非常顺手，能否也支持一下centos 6.10?

**Comment by linrongbin16** [comment]
昨天添加了centos的安装脚本，自己在centos-8虚拟机上测试，发现很多软件版本太老，导致gvim打不开。
估计centos-6就更加无法正常运行了，所以目前还是没办法支持centos。
你可以尝试在centos上把 *setting-vim/basic.vim* 这个文件copy到 *~/.vimrc*，这个文件是没有任何插件的一份基础配置，如果只是在服务器上使用vim的话，差不多也够用。
