### ISSUE TITLE
Should lin.vim move to neovim-only, drop support for vim?

### ISSUE THREAD

**Issue by linrongbin16** [linrongbin16/lin.vim#21]
Vim 9 is released, but I don't feel like I want to use it. Actually in latest 2 years, I'm just using neovim with neovide, no more vim. Neovim 0.6+ has much better performance, and there're many new lua plugins that has cool feature and good performance.

So I want to ask you, should lin.vim move to neovim-only, drop support for vim?

**Comment by liaoliaopro** [comment]
刚fork完并折腾顺手。。。但是，还是支持+期待。

**Comment by liaoliaopro** [comment]
neovim试用了几回，但都出现一些奇奇怪怪的问题，后来都回退到vim。很期待再尝试尝试。

**Comment by linrongbin16** [comment]
@liaoliaopro , 用最新stable 版本 neovim 0.7.2，然后再装一个 neovide GUI，我用起来比vim要好
我最开始接触neovim的时候，大概0.3可能，好像也有一些问题，但后来问题都消失了。似乎是自己配置有点问题

你用 lin.vim 的话，只要安装了 neovim 0.7.2，就也是可以启动的，用起来应该跟vim是一模一样的。就是UI界面会更好看，性能更好。

**Comment by liaoliaopro** [comment]
我试用了neovim 0.8.0-dev。 遇到一些问题，比如：rust文档中的分隔符"--"展示会多出一些折行；floatterm插件竖屏显示时，<c-w>没办法跳转窗口等等，vim中都正常。折腾了几下弄不好，就退回去了。回头我再试试neovide，谢谢推荐。

lin.vim很棒，看了文档介绍后我直接抛弃了自己用了多年的dotfiles配置，以前各种插件设置冲突处理起来很花时间。用上lin.vim，哇，这就是我想要的东西，感觉那个丝滑。调整了一些自己习惯的快捷键和插件配置好很快就用顺手了。

安装包有个小建议，安装包中好像vim/nvim是自动安装的，能否做成可选，默认不安装或询问一下。一般情况下，vim/nvim可能使用者已经安装好了。我自己安装的时候发现安装过程卡了很长时间，一看是从ppa上在拉vim/nvim。

**Comment by linrongbin16** [comment]
@liaoliaopro , 做成选装的就是 要在 install.sh 里面增加很多跟用户的交互逻辑，我实在是。。。懒得搞。毕竟bash和powershell写起来都不算很愉快的体验。

**Comment by linrongbin16** [comment]
@liaoliaopro , 考虑了一下，确实lin.vim目前一个比较大值得去优化的地方就是安装脚本，做成一个交互式安装脚本更符合一般用户的需求。
