### ISSUE TITLE
markdown preview

### ISSUE THREAD

**Issue by crazyseabiscuit** [linrongbin16/lin.vim#22]
Hi 

I am new to lin vim , just want to give it a quick try , i press FN + 8 and expect to see some markdown preview panel , but it doesn't work for me , I am using MacBook Pro.

Can you pls take a look?

**Comment by linrongbin16** [comment]
@crazyseabiscuit 
please also try f11 or f12.
I have changed hot keys these days (forgot to update readme).

**Comment by linrongbin16** [comment]
Please try re-install lin.vim again by:

```
$ cd ~/.vim
$ git pull origin master
$ ./install.sh
```

Maybe some commits have bugs, and it should be fixed later.

Please also try to open `~/.vim/setting.vim` file to check the mapping `nnoremap <F8> :<C-u>MarkdownPreview<CR>`, make sure it's binding to F8.

**Comment by linrongbin16** [comment]
Not active.
