### ISSUE TITLE
lualine reports error while opening rust project

### ISSUE THREAD

**Issue by liaoliaopro** [linrongbin16/lin.vim#23]
![image](https://user-images.githubusercontent.com/2876615/191419466-2b0ebb03-bf65-4e3c-aa73-f05e089cf98d.png)

neovim + latest lin.vim,  plugin lualine reports "illegal character" error  while opening rust project.

**Comment by linrongbin16** [comment]
please try re-install lin.vim again by:

```
cd ~/.vim
git pull origin master
./install.sh
```

可能我某次更新出bug了，请重新安装一下

**Comment by liaoliaopro** [comment]
git pull upstream master后，还是报类似的错误，但行数不一样了。。。

![image](https://user-images.githubusercontent.com/2876615/201302167-98cebf4d-9718-4656-bd08-ddc144fa0309.png)

**Comment by linrongbin16** [comment]
试一下进入vim之后运行 ` :PlugUpdate!` 会更新所有vim plugins

**Comment by liaoliaopro** [comment]
运行了的，plugin是最新。配置也没看出所以然来。先替换成lightline了，工作正常。

**Comment by linrongbin16** [comment]
not active
