### ISSUE TITLE
两个关于fzf搜索的问题

### ISSUE THREAD

**Issue by liaoliaopro** [linrongbin16/lin.vim#24]
有两个比较高频的fzf搜索场景没找到用法，请教一下：

1. 自动打开上一次搜索结果。有时搜索结果出来，处理了一个搜索项，想处理下一个时，得从头输入关键字重新搜索一遍。 LeaderF插件有个recall previous result，比较方便。

2. 对光标所在的字符串进行搜索。这个也比较高频，现在每次得手打一遍。

感谢答疑。

**Comment by linrongbin16** [comment]
hi @liaoliaopro
非常好的问题，我自己也遇到了这两个问题。
我暂时没办法立刻解决这两个问题。

第一个问题的思路，是需要调研一下，fzf能不能查询所有搜索历史。
第二个问题的思路，是设计一个快捷键 比如 `<space>gx`，可以直接用fzf搜索光标当前位置下的单词。

后面想想办法解决吧！

**Comment by qinjianwei** [comment]
只会基本的vim单文件操作。装了之后，感觉vim变复杂了。有相关教程吗？大佬

**Comment by linrongbin16** [comment]
额。。。就是readme，或者从 .vimrc 文件开始，一行一行google查文档。

**Comment by qinjianwei** [comment]
完全不会用了，请问怎么卸载呀

**Comment by linrongbin16** [comment]
Hi @liaoliaopro 

对于第2个问题，快捷键直接搜索光标所在的单词，我最新的commit里，增加了 `<Leader>gw` ，可以直接搜索光标所在单词的文本。
详情可以看readme search这一节。

**Comment by linrongbin16** [comment]
Issue 1 will not done for now.
