### ISSUE TITLE
[Question] How to update to the latest upstream?

### ISSUE THREAD

**Issue by tan-wei** [linrongbin16/lin.vim#26]
When the upstream is updated (a.k.a the repo itself), how do I update? Just do `git pull` and then `:PlugUpdate`?

Thanks.

**Comment by linrongbin16** [comment]
Re-install and update all vim plugins:
```
$ cd ~/.vim && git pull
$ ./install.sh
```

Open vim and execute: `:PlugUpdate!` to force update all plugins.

**Comment by linrongbin16** [comment]
To update lin.vim, please re-install it by (notice: this could overwrite your `~/.vim/setting.vim` and `~/.vim/plugin.vim` file)

```
$ cd ~/.vim
$ git pull origin master
$ ./install.sh
```

To update vim plugins, please open vim and execute: `:PlugUpdate!` to force update all plugins.

**Comment by tan-wei** [comment]
Clear. Thanks.
