### ISSUE TITLE
Error detected while processing CursorHold Auto commands for "*"

### ISSUE THREAD

**Issue by sxwgit** [linrongbin16/lin.vim#3]
您好，我按照GitHub上的命令直接安装了lin.vim，但是当我打开任意一个文件夹时，得到了如标题的错误
```
Error detected while processing CursorHold Auto commands for "*"
E117: Unknown function: CocActionAsync
```

我ubuntu的版本是16.04，vim的版本是7.4，这个机器以前没有安装过vim相关的配置，应该不存在干扰相关的问题。
请问如何解决该错误呢？

这个插件会在zshrc中source一个新的配置文件，但是我本来有用zsh，这个配置文件和我现有的有冲突，所以我删除了在zshrc文件中添加的“souce ~/.linvimrc”。不知道能否在默认安装的时候，选择是否修改zsh文件呢？

**Comment by linrongbin16** [comment]
1. CocActionAsync问题：安装完成第一次启动时，lin.vim还需要一个自动安装coc.nvim扩展的初始化过程。忽略这时候的报错，等所有扩展安装完成，关闭vim再重新打开，应该就正常了。
2. 环境变量问题：推荐你还是别删除`source ~/.linvimrc`这句，而是直接编辑`~/.linvimrc`，修改或者删除冲突的部分。

**Comment by sxwgit** [comment]
我更新了vim的版本，从vim7.4更新到了vim8.2，一些插件可以正常下载，标题中出现的问题也消失了。
但是我每次启动vim的时候，会出现一个新的warning:
`LeaderF requires Vim compiled with python and/or a compatible python version.`
我当前的Python版本是Python 3.7.6。
可能在安装的时候，需要确定相关软件的版本？

**Comment by linrongbin16** [comment]
需要vim --version看一下，最新版vim可能是跟python3.8或3.9一起编译的，就需要你的python也是对应的3.8或3.9。
其实ubuntu每个版本的系统上的gcc、clang、vim、python3等工具链都是配套的。主要还是因为ubuntu 16.04太老了，导致你升级了vim，就还需要升级对应的python等软件

**Comment by linrongbin16** [comment]
其实ubuntu每个版本的系统上的gcc、clang、vim、python3等工具链都是配套的。主要还是因为ubuntu 16.04太老了，导致你升级了vim，就还需要升级对应的python等软件

**Comment by sxwgit** [comment]
因为用的是服务器，所以ubuntu版本号是16，不好升级。有时间，我用wsl装一个20的ubuntu试一下。
如果可以的话，你可以在readme里面备注一下相关软件的版本，这样可以避免一些bug的出现。

**Comment by linrongbin16** [comment]
对了，一开始如果你没升级vim，就用vim7.4，是不是有一些coc.nvim的软件也不能用？

**Comment by sxwgit** [comment]
![image](https://user-images.githubusercontent.com/21139332/103184218-051cef80-48f2-11eb-85ab-cb7ecc399b7e.png)
我以前一直用的是原生vim，没有试过。不过我在vim7.4版本下面，使用`source ~/.vimrc`, 得到了如上报错，可能对你有些帮助

**Comment by linrongbin16** [comment]
嗯，我这边增加一个测试列表，把测试通过的、未通过的操作系统和软件版本列一下，这样有些明确不支持的操作系统就可以提前告知用户。

**Comment by sxwgit** [comment]
多谢了，如果你需要的话，我可以提供我当前使用软件的版本信息

**Comment by linrongbin16** [comment]
好的啊，请你列一下OS、vim、python、node这4个软件包括版本的一些信息。我标记在README里。

**Comment by sxwgit** [comment]
Linux 4.15.0-45-generic；
Ubuntu 16.04.01；
Vim Vi IMproved 7.4；
Python 3.7.6 ；
node v14.15.3。

**Comment by linrongbin16** [comment]
我自己在虚拟机上测试了一下ubuntu 16.04，发现coc.nvim是不支持vim 8.0以下的，所以导致你遇到这个 CocActionAsync 的错误。缺少coc.nvim基本上大部分功能都没办法用了。我在README上说明一下软件的版本限制。
