### ISSUE TITLE
这一轮大改什么思路(好奇询问)？

### ISSUE THREAD

**Issue by liaoliaopro** [linrongbin16/lin.vim#30]
纯属好奇，最近打鸡血更新，是要往哪里去呀？

**Comment by linrongbin16** [comment]
主要是install脚本的更新，对用户没什么特别大影响：
1. install脚本增加了许多选项。可以看readme里more options。
2. install.ps1增加了很多软件的自动下载安装，简化了windows下的软件安装依赖。（理想状态是能做到像linux下一行代码就完全安装好）
3. review了一下现在的配置脚本，更新了一些过时的、冗余的，甚至是错误的配置。（这部分只有三四个小众功能，可能大家没用到所以都没发现）

**Comment by liaoliaopro** [comment]
谢谢，了解了。
