### ISSUE TITLE
Unknown function: ShowDocumentation

### ISSUE THREAD

**Issue by liaoliaopro** [linrongbin16/lin.vim#38]
更新最新的版本后，shift+K，报告错误： Unknown function: ShowDocumentation。临时按以下修改后能正常工作。

“nnoremap <silent> K :call ShowDocumentation()<CR>
 nnoremap K :call CocActionAsync('doHover')<CR>

**Comment by linrongbin16** [comment]
Fixed in commit: https://github.com/linrongbin16/lin.vim/commit/4c0ae836502637541243c07edc4d00203b6bf6ff

Please pull master.
