### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by yllr78** [linrongbin16/lin.vim#4]
zhihu上拜读了你的文章，来学习一下你的配置 ：）
现在有个小问题想请教：
win7系统上总是不显示nerd字体图标，我用的字体和你相同，是nerd-hack字体，不知你是怎么解决的？在arch上相同配置可以正常显示。  主要是那个nerdtree上的文件类型图标。

**Comment by linrongbin16** [comment]
默认的guifont配置是：
```
" 7. GUI fonts
if has("win32")
    " win32
    set guifont=Hack\ NF:h9
elseif has("mac")
    " macos
    set guifont=Hack\ Nerd\ Font\ Mono:h12
else
    " linux, unix
    set guifont=Hack\ Nerd\ Font\ Mono\ 10
endif
```
要仔细看下你的windows上的NerdFont字体到底叫什么？

**Comment by linrongbin16** [comment]
或者你可以按照readme里的方法，从这里 https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip 下载，然后手动安装下面这4个字体：

* `Hack Regular Nerd Font Complete Mono Windows Compatible.ttf`
* `Hack Italic Nerd Font Complete Mono Windows Compatible.ttf`
* `Hack Bold Italic Nerd Font Complete Mono Windows Compatible.ttf`
* `Hack Bold Nerd Font Complete Mono Windows Compatible.ttf`
