### ISSUE TITLE
use updated verion of neovim when intall for old linux release(such as debian 9)

### ISSUE THREAD

**Issue by weyllor** [linrongbin16/lin.vim#40]
it seems the `install .sh` use `apt install neovim` to install, but for old debian verion(9), the neovim version is 0.1.x, that is to old to use.

Could you plz use the install methd of https://github.com/neovim/neovim/blob/master/INSTALL.md#linux.

**Comment by linrongbin16** [comment]
hi @weyllor , please use the next generation: https://github.com/linrongbin16/lin.nvim.

It's a maintained version for Neovim.
