### ISSUE TITLE
如何关闭自动format?

### ISSUE THREAD

**Issue by cnjswwxbtcc** [linrongbin16/lin.vim#8]
在保存文件的时候会自动的format代码格式，
不过用于已经存在的项目上的时候，一些固定格式被改掉了，就显得很奇怪，所以想请教下这个设置怎么改。

**Comment by linrongbin16** [comment]
在 `~/.vim/coc-settings.json` 中 编辑 `coc.preferences.formatOnSaveFiletypes` 这一项，删除你不想自动格式化的文件类型
